#!/bin/bash


[ ! -v KLOG_COLOR ] && KLOG_COLOR=1
[ ! -v KLOG_LEVEL ] && KLOG_LEVEL=TRACE

export KLOG_COLOR KLOG_LEVEL

ROOTDIR="$(pwd)"
cd `dirname "$0"` && cd ..

if [ "$OSTYPE" == "linux-gnu" ]; then
  TARGET=linux
else
  TARGET=macos
fi

if [ "$HOSTTYPE" == "x86_64" ]; then
  TARGET=${TARGET}X64
else
  TARGET=${TARGET}Arm64
fi

LIBS=$(realpath .)/core/build/bin/$TARGET/kssh2DebugShared:/usr/lib:/usr/local/lib



echo target is $TARGET libs: $LIBS
if [ "$OSTYPE" == "linux-gnu" ]; then
  export LD_LIBRARY_PATH=$LIBS
else
  export DYLD_LIBRARY_PATH=$LIBS
fi

export SSH2_LIBS="/usr/local/lib/libssh2.dylib:$(realpath .)/core/build/bin/$TARGET/kssh2DebugShared"

ARGS="-Djava.library.path=$(realpath .)/core/build/bin/$TARGET/kssh2DebugShared:/usr/lib:/usr/local/lib"

export MESSAGE="This is my message at `date`"

TMPFILE=`mktemp`
(./gradlew --console=plain :core:linkKssh2DebugShared$TARGET :demo:getShadowJar || exit 1) | tee $TMPFILE
JARFILE=`cat $TMPFILE | awk '/shadowJar:/  {print $2}'`
echo jarfile: $JARFILE
rm $TMPFILE
echo changing to dir $ROOTDIR
cd "$ROOTDIR"
echo LD_LIBRARY_PATH = $LD_LIBRARY_PATH
echo DYLD_LIBRARY_PATH = $DYLD_LIBRARY_PATH
exec java $ARGS -jar $JARFILE "$@"


